### ISSUE TITLE
Google Calendar - time zone

### ISSUE THREAD

**Issue by kirilovich-vlad** [cssbristol/cssbristol.github.io#174]
When I import CSS calendar to my Google Calendar account (using a URL on CSS website), starting and ending times of every event are erroneously incremented by 1 hour. There are no such issues with any other calendar added using a URL. 
If I check the calendar properties, Google shows that this calendar uses GMT+00:00 instead of GMT+01:00 that is being used in the UK right now - there is no option to change a time zone for a specific calendar.
Same calendar works fine in Outlook.
Is there anything that can be done for better compatibility, like adjusting a time zone of the source calendar?

**Comment by a6-webm** [comment]
Sorry for the super late reply, I really need to enable notifications on this repo...

I've added a specifier for the timezone to the calendar now, but I really can't get it to cooperate when I resubscribe to it.

My first instinct is some cache that Google is pulling from, but I will keep at this problem until it's fixed.

For now, if in doubt, double check the website.

**Comment by a6-webm** [comment]
Well I've certainly fixed the time zone issue, but it seems the lack of updating is an issue with Google Calendar, and has been going on for years with no fix from Google.

All I could find really that tries to fix anything is this <https://github.com/derekantrican/GAS-ICS-Sync>.
