### ISSUE TITLE
Add Wise 's Software Engineer Intern job listing

### ISSUE THREAD

**Issue by m-salmankhan** [cssbristol/cssbristol.github.io#178]
_This issue was created automatically by PowerAutomate_

## Company:
Wise
## Logo:
https://d21buns5ku92am.cloudfront.net/69645/images/470455-Frame%2039263-cdfad6-original-1677657684.png
## Title:
Software Engineer Intern

## Application Link/Email:
https://grnh.se/37de85341us - this is a referral link 

## Application Deadline:
2023-12-31

## Employment Type:
Internship (e.g. over summer)

## Salary:
£36000

## Location:
London, Hybrid (UK)

## Industry:
Software Engineering

## Company Overview:
Whether you’re sending money to another country, spending money abroad, or making and receiving international business payments, Wise is on a mission to make your life easier and save you money.

Since it was founded in 2010, 5,000+ people work at Wise, from 125 nationalities, in 17 global locations. You’ll be part of Wise’s global mission to build an open, fair, and human financial system – to make money without borders the new norm. Because people without borders need money without borders.

## Requirements:
Must haves:
- You are graduating in 2025 from a Bachelors or Masters degree. This might be in Computer Science, or any other STEM subject
- Able to start a 10 week internship from the 24th of June 2024 until the 30th of August 2024
- You are available to start a full time graduate role in September 2025
- Knowledge of computer science fundamentals including data structures, algorithms and software design
- Familiarity of data models with SQL
- Knowledge of working with RESTful Web Services
- A basic knowledge in modern web technologies and a strong interest in web development
- A self-started side project(s) that you are proud to talk about
- Great communication skills and the ability to articulate complex, technical concepts to a non-technical audience
- Curious, keen to learn and proactive by nature
You believe in and follow best coding practices and code reviews
- You are open to and value feedback in order to improve
- Eligible to work in London

Nice to haves: 
- Experience in web or microservice development, from a previous internship or project
- Familiarity with any major programming languages like Java/JavaScript/Python/Kotlin/Swift (we are more focused on your willingness to learn new technologies)
- A strong product mindset and passion for user experience. You prioritise work with customers in mind, and make data-driven decisions to fix customer pain-points

## Responsibilities:
- Work cross-functionally in squads who are vital to driving the mission of our business forward
- Create clear and helpful interfaces, whilst maintaining consistency, maintainability and performance
- Understand the challenges our customers face and set out to solve them

Here’s one of the former interns to tell you more about what all that means! https://www.wise.jobs/2021/09/24/wise-interns-a-conversation-with-jasleen-matharu/

## Other information:
You can check out more about us, the interview process and how we work and why we do what we do at https://wise.jobs - feel free to reach out to me (mitch.lui@wise.com or https://mitchlui.dev/linkedin) if you have any questions! 

[Full form submission details (including contact details)](https://uob.sharepoint.com/:t:/t/grp-CSSCommittee213/Echn10w7FUxBrWCydBLjaRYBB31C_I2lqTk3K65RQN5DzQ). NB: This is not accessible by everyone.

If you have questions about this listing, view the link above to see who to contact about this.

**Comment by a6-webm** [comment]
Listed
