### ISSUE TITLE
Site is Down

### ISSUE THREAD

**Issue by ben-marshall** [cssbristol/cssbristol.github.io#2]
Upon visiting the site via https://cssbristol.co.uk/ users are greeted with a "Privacy Error" message from Google Chrome.

When clicking through or "proceed anyway" users get the default cPanel error page.

The cssbristol.github.io address sends users to the "new site coming soon" page, with no way to view the new site, even in preview.

**Comment by JulianLaval** [comment]
:( On it!

**Comment by rossng** [comment]
Sadly Github pages doesn't officially support https, so there's not much we can do at the moment. I'll keep an eye out for solutions.

**Comment by macqm** [comment]
What about CNAME settings for the domain to redirect https:// to http:// ?

**Comment by rossng** [comment]
@macqm how would we do that? I didn't think it was possible with DNS.

Here's the current zone file:

```
@ 1800 IN A 192.30.252.153
@ 1800 IN A 192.30.252.154
old 10800 IN CNAME webredir.vip.gandi.net.
www 1800 IN CNAME cssbristol.github.io.
@ 28800 IN MX 3 ALT1.ASPMX.L.GOOGLE.COM.
@ 28800 IN MX 3 ALT2.ASPMX.L.GOOGLE.COM.
@ 28800 IN MX 1 ASPMX.L.GOOGLE.COM.
@ 28800 IN MX 5 ASPMX2.GOOGLEMAIL.COM.
@ 28800 IN MX 5 ASPMX3.GOOGLEMAIL.COM.
@ 28800 IN MX 5 ASPMX4.GOOGLEMAIL.COM.
@ 28800 IN MX 5 ASPMX5.GOOGLEMAIL.COM.
```
