### ISSUE TITLE
HTTPS Error

### ISSUE THREAD

**Issue by johng** [cssbristol/cssbristol.github.io#27]
Security warning when visiting https://cssbristol.co.uk

**Comment by rossng** [comment]
> HTTPS is not supported for GitHub Pages using custom domains.

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by johng** [comment]
We could use Amazon S3 instead, we don't have to host on pages?

**Comment by djmylt** [comment]
I think you can also do it using GitLab Pages: https://docs.gitlab.com//ce/user/project/pages/introduction.html#secure-your-custom-domain-website-with-tls

**Comment by harrymt** [comment]
We can use cloudflare to setup https for github pages. https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/
