### ISSUE TITLE
New git tutorial overflows off the page on mobile

### ISSUE THREAD

**Issue by k4l397** [cssbristol/cssbristol.github.io#35]
![cssbristol co uk-tutorials-git- galaxy s5](https://user-images.githubusercontent.com/4959969/31768801-c84ac200-b4c8-11e7-86d2-c4598be5e389.png)

**Comment by louisheath** [comment]
Hi Kyle thanks for pointing this out, turns out it's a problem for the SSH tutorial too. Will look into it now

**Comment by danjones1618** [comment]
This has now been _fixed_. It seams that it was due to the events page and tutorials page sharing the same styling. I will be doing an update to the styling of the tutorial's home page imminently along with improvements to the event pages.

**Comment by k4l397** [comment]
@danjones1618 I still seem to have the issue on chrome (not checked on other browsers).

I've briefly investigated and it seems changing .page_section to `display: block` OR removing the `flex-direction: column` attribute from that class fixes that particular page (and others like the one mentioned in #51 )

This would break other parts of the site though and I haven't looked into exactly why that fix works.

**Comment by danjones1618** [comment]
@k4l397 I see what you mean. I'll work on getting this fixed asap as I'm currently refactoring parts of the website with the "post" pages being next on the radar.
