### ISSUE TITLE
Unit Choices Page

### ISSUE THREAD

**Issue by johng** [cssbristol/cssbristol.github.io#36]
CSS Should make it easier for picking units.

The current system involves ad hoc discussion on our Facebook group which is lost over time and not accessible to members who are not part of the group.

For each unit there should be a comments section, along with a short summary describing the unit. 

There should also be a link to the official questionnaire results which we collected last year.

This page could become part of a general push to increase communication between the student staff body.

**Comment by louisheath** [comment]
Sounds like a good idea,
Do we want people to be able to sign up in order to comment? This will also probably involve some back end. Either I need to work out Heroku/AWS or we need to move elsewhere.
An alternative could be to have a subreddit with a thread for each unit ?

**Comment by johng** [comment]
We now have a wiki page hosted by the University, which is behind SSO
