### ISSUE TITLE
Cross-platform Gemfile.lock

### ISSUE THREAD

**Issue by rossng** [cssbristol/cssbristol.github.io#39]
On Windows (and only Windows), the `wdm` gem is required. Bundler will automatically add this to the Gemfile.lock. This means developers on different platforms are likely to keep adding and removing `wdm` from Gemfile.lock.

It might be possible to resolve this with some incantation of `bundle lock --add-platform`.

**Comment by danjones1618** [comment]
Is this still a problem? I don't use windows

**Comment by rossng** [comment]
Doesn't seem like it's auto-installed now, so that particular problem is gone. It does still warn about it when running, but it's optional to install it anyway.
