### ISSUE TITLE
Move from Cloudflare HTTPS to native GitHub Pages HTTPS

### ISSUE THREAD

**Issue by rossng** [cssbristol/cssbristol.github.io#41]
GitHub finally added [proper support for HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/) yesterday.

**Comment by louisheath** [comment]
Setting it up on personal site first so I know what not to break

**Comment by th0mas** [comment]
Can't enable HTTPS natively on GitHub while Cloudflare proxying is enabled.  
![image](https://user-images.githubusercontent.com/9089056/147128956-96d13b34-2198-4e97-844d-718068ec4ccf.png)

Hesitant to disable the cloudflare proxy as we'd have effectively no HTTPS for a few hours while the DNS changes propagate and are recognised by GitHub/LetsEncrypt. We'd also loose out on analytics, most of our visitors block the javascript cloudflare analytics client.

@m-salmankhan your call on if you reckon its worth it

**Comment by 14ROVI** [comment]
we use Cloudflare for other stuff so i would rather it all stay in one place
