### ISSUE TITLE
Job Update Request

### ISSUE THREAD

**Issue by tom-toka** [cssbristol/cssbristol.github.io#58]
Hi,

We posted a new job on the CSS website https://cssbristol.co.uk/jobs/2019-06-26-3d-printing-bath/

1. Could the Job Title be updated to Software Developer - seems like it got changed to Automation Engineer
2. Could we have the company logo updated to the attached
3. In the opening paragraph there was a grammatical error. Can it be replaced with the following: "We’re looking for an ambitious Software Developer to join a fast-growing team and partner on the creation of TOKA® virtual surgical planning software. TOKA is hiring a C++ software engineer to build the ground-breaking application that blends imaging techniques with 3D printing to treat early stage osteoarthritis. This is your chance to advance novel technology that will benefit mobility, health and quality of life for patients of all demographics worldwide."
4. The Job responsibilities don't seem to have been broken out in lines as expected. Should they be on separate lines?

Thank you
Tom

<img width="616" alt="3D Metal Printing" src="https://user-images.githubusercontent.com/52285440/60268345-1d1e4800-98e4-11e9-8202-5d065c0c0823.png">

**Comment by danjones1618** [comment]
Hi, changes have been made as per your request.

**Comment by tom-toka** [comment]
Excellent thank you so much Daniel

 

Tom
