### ISSUE TITLE
Lists in markdown

### ISSUE THREAD

**Issue by jgbdev** [cssbristol/cssbristol.github.io#7]
I'm trying to add a list to a markdown file using the style guide specified in the Jekyll [docs](http://www.jekyllnow.com/Markdown-Style-Guide/)

However the list items are rendered with dashes instead of bullet points or numbers.

**Comment by rossng** [comment]
This is [expected behaviour](https://github.com/cssbristol/cssbristol.github.io/blob/79de729917f5cad158258afd8cb482cd72823fe9/_sass/_articles.scss#L27) (unless the list really isn't rendering as a `ul`). 

If you have a particular style in mind, though, you can submit a PR to change it!
